PermissionAndAuthorization/PermissionAndAuthorization/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('permissionauthorization/', include('SignUpForm.urls')),
]

PermissionAndAuthorization/SignUpForm/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('signup/', views.Signup, name = 'signup'),
    path('login/', views.Login, name = 'login'),
    path('dashboard/', views.UserDashboard, name = 'dashboard'),
    path('logout/', views.Logout, name = 'logout'),
]

PermissionAndAuthorization/SignUpForm/models.py
from statistics import mode
from django.db import models
from matplotlib.pyplot import title


class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100)

PermissionAndAuthorization/SignUpForm/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import SignupForm, EditUserProfile
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.models import User, Group
# Signup Form


def Signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            messages.success(request, 'Account Created Successfully !!!')
            user = form.save()
            group = Group.objects.get(name = 'editor')
            user.groups.add(group)
    else:
        form = SignupForm()
        print('This came form GET Method')
    return render(request, 'SignUpForm/Signup.html', {'form': form})


#Login
def Login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            print('This came from POST method')
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                passwd = form.cleaned_data['password']
                user = authenticate(username=uname, password=passwd)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'Logined Successfully !!!')
                    return HttpResponseRedirect('/permissionauthorization/dashboard/')
        else:
            print('This came from GET Method')
            form = AuthenticationForm()
        return render(request, 'SignUpForm/Login.html', {'form': form})
    else:
        return HttpResponseRedirect('/permissionauthorization/dashboard/')

# Dashboard
def UserDashboard(request):
    if request.user.is_authenticated:
        messages.success(request, 'You have logout ???')
        return render(request, 'SignUpForm/Dashboard.html', {'name':request.user.username})
    else:
        return HttpResponseRedirect('/permissionauthorization/login')


# Logout Form


def Logout(request):
    logout(request)
    return HttpResponseRedirect('/permissionauthorization/login/')

PermissionAndAuthorization/SignUpForm/templates/SignUpForm/Dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static "SignUpForm/css/bootstrap.min.css" %}">
	<link rel="stylesheet" type="text/css" href=" {% static 'SignUpForm/css/style.css' %} ">
	<title>Dashboard</title>
</head>
<body>
	<div class = "container">
		<div class = "alert text-center alert-danger">
			<h1>User dashboard</h1>
			<h2>Welcome {{ name }}</h2>
		</div>
		<div class = "form-group">
			
			{% if perms.SignUpForm.delete_blog %}
			    
			    <input type="button" name = "button" class = "btn btn-outline-dark" value = "Delete">
			{% else %}
            
            <div class="alert text-center alert-primary">
			<h3>Sorry ! <b style="color:orangered"> {{name}} </b> <br> You Do Not Have Delete Permission</h3></div>
			
			{% endif %}

			{% if perms.SignUpForm.add_blog %}
			    
			    <input type="button" name = "button" class = "btn btn-outline-dark" value = "Add">
			{% else %}
            
            <div class="alert text-center alert-info">
			<h3>Sorry ! <b style="color:orangered"> {{name}} </b> <br> You Do Not Have Add Permission</h3></div>
			
			{% endif %}
			

			<a href="{% url 'logout' %}" class = "btn btn-outline-success">Logout</a>
		</div>
	</div>


<script type="text/javascript" src="{% static "SignUpForm/js/jquery-3.6.0.js" %}"></script>
<script type="text/javascript" src=" {% static "SignUpForm/js/popper.min.js" %}"></script>
<script type="text/javascript" src=" {% static "SignUpForm/js/bootstrap.min.js" %}"></script>
</body>
</html>

PermissionAndAuthorization/SignUpForm/templates/SignUpForm/Login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static "SignUpForm/css/bootstrap.min.css" %}">
	<link rel="stylesheet" type="text/css" href=" {% static 'SignUpForm/css/style.css' %} ">
	<title>Login</title>
</head>
<body>
	<div class="container mt-5">
			<div class="alert text-center alert-danger">
				<h1>Login Form</h1>
			</div>
			<form action="" method="POST" novalidate>
				{% csrf_token %}
                 {% if form.non_field_errors %}
                     {% for error in form.non_field_errors %}
                    
                    <p> {{ error }} </p>
                     	
                     {% endfor %}
                 
                 {% endif %}
				{% for fm in form %}

				{{ fm.label.tags }}
				{{ fm }}
				{{ fm.errors | striptags }} <br><br>

				{% endfor %}
				<div class="form-group">
					<input type="submit" name="submit" value="Login" class="btn btn-outline-danger" style="width:20%;height:40px;">
					<a href=" {% url 'signup' %}"><input type="button" name="button" value="Signup" class="btn btn-outline-primary" style="width:20%;height:40px;"></a>
				</div>

			</form> <br>
	</div>

<script type="text/javascript" src="{% static "SignUpForm/js/jquery-3.6.0.js" %}"></script>
<script type="text/javascript" src=" {% static "SignUpForm/js/popper.min.js" %}"></script>
<script type="text/javascript" src=" {% static "SignUpForm/js/bootstrap.min.js" %}"></script>
</body>
</html>

PermissionAndAuthorization/SignUpForm/templates/SignUpForm/Signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static "SignUpForm/css/bootstrap.min.css" %}">
	<link rel="stylesheet" type="text/css" href=" {% static "SignUpForm/css/style.css" %} ">
	<title>Signup</title>
</head>
<body>
	<div class="container mt-5">
		<div class="row">
			<div class="alert text-center alert-danger mt-2" id = "do">
				<h1>Creating Resgistrationg Form Using User Creation form </h1>
			</div>
		</div>
		<form action="" method="POST" novalidate>
			{% csrf_token %}
			
			{% if form.non_field_errors %}
			{% for error in form.non_field_errors %}

			<p> {{ error }} </p>

			{% endfor %}

			{% endif %}

			{% for fm in form  %}
			{{ fm.label_tag }}
			{{ fm }}
			<span>{{ fm.errors | striptags }} </span> <br><br>

			{% endfor %}
			<div class="form-group">
				<input type="submit" name="submit" value="Signup" class="btn btn-outline-success" style="width:30%;height:40px;">
				<a href="{% url 'login' %}"><input type="button" name="button" value="Login" class="btn btn-outline-danger" style="width:30%;height:40px;"></a>
			</div>
		</form>
		{% if messages %}
		{% for message in messages %}
		<small {% if message.tags %} class="{{message.tags}}"> {% endif %}
		{{ message }} </small>
		{% endfor %}
		{% endif %}
	</div>

<script type="text/javascript" src="{% static "SignUpForm/js/jquery-3.6.0.js" %}"></script>
<script type="text/javascript" src=" {% static "SignUpForm/js/popper.min.js" %}"></script>
<script type="text/javascript" src=" {% static "SignUpForm/js/bootstrap.min.js" %}"></script>
</body>
</html>